<?php
/**
 * 
 * @admin ~~// this is the file for all arrays
 * 
 */
if ( ! defined( 'ABSPATH' ) ) exit;
// Live Copy,Vertical Split Slideshow,Advanced Posts Tab,Product Vendors,Reveal Effects
// ====================================================
// For new show
$whatsNew = [
    [
        'img'=>'../../assets/admin/dashboard/images/small-logo.png',
        'name'=>esc_html__('Live Copy','bwd-elementor-addons'),
        'desc'=>esc_html__('Copy-paste Elementor designs across sites easily.','bwd-elementor-addons'),
    ],
    [
        'img'=>'../../assets/admin/dashboard/images/small-logo.png',
        'name'=>esc_html__('Vertical Split Slideshow','bwd-elementor-addons'),
        'desc'=>esc_html__('Create vertical split-screen image slideshows.','bwd-elementor-addons'),
    ],
    [
        'img'=>'../../assets/admin/dashboard/images/small-logo.png',
        'name'=>esc_html__('Advanced Posts Tab','bwd-elementor-addons'),
        'desc'=>esc_html__('Display posts in tabbed, organized layout.','bwd-elementor-addons'),
    ],
    [
        'img'=>'../../assets/admin/dashboard/images/small-logo.png',
        'name'=>esc_html__('Product Vendors','bwd-elementor-addons'),
        'desc'=>esc_html__('Manage and showcase multiple product vendors.','bwd-elementor-addons'),
    ],
    [
        'img'=>'../../assets/admin/dashboard/images/small-logo.png',
        'name'=>esc_html__('Reveal Effects','bwd-elementor-addons'),
        'desc'=>esc_html__('Add animated reveal effects to elements.','bwd-elementor-addons'),
    ]
];
// ====================================================
// For general
$generalWidgets = [
    [
        'name'=>esc_html__('Meet The Team','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-meet-the-team',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/mtt_documentation/',
        'demo'=>'https://bestwpdeveloper.com/meet-the-team',
        'video'=>'https://youtu.be/pcCObKvhhrk',
        'free_pro'=>true,
        'new'=>false,
        'used'=>1,
    ],
    [
        'name'=>esc_html__('Testimonials','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-testimonials',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bwdt-documentation/',
        'demo'=>'https://bestwpdeveloper.com/testimonial-addon-for-elementor',
        'video'=>'https://youtu.be/-8Amde3m_m0',
        'free_pro'=>true,
        'new'=>false,
        'used'=>2,
    ],
    [
        'name'=>esc_html__('Creative Button','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-creative-button',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bcb_documentation/',
        'demo'=>'https://bestwpdeveloper.com/creative-button',
        'video'=>'https://youtu.be/MH7n_vCnaIw',
        'free_pro'=>true,
        'new'=>false,
        'used'=>3,
    ],
    [
        'name'=>esc_html__('Accordion','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-accordion',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/ba_documentation/',
        'demo'=>'https://bestwpdeveloper.com/accordion-addon-for-elementor',
        'video'=>'https://youtu.be/LTNVB6LJ88Y',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Masking Effect','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-masking-effect',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bme_documentation/',
        'demo'=>'https://bestwpdeveloper.com/bwd-masking-effect',
        'video'=>'https://youtu.be/vPXPx6rAx2w',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Service Showcase','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-service-showcase',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bss_documentation/',
        'demo'=>'https://bestwpdeveloper.com/service-addon-for-elementor',
        'video'=>'https://youtu.be/Q2Gb1ouZhmc',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Promo Box','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-promo-box',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bpb_documentation/',
        'demo'=>'https://bestwpdeveloper.com/promo-box',
        'video'=>'https://youtu.be/DUb42fYHajE',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Service Flip Box','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-service-flip-box',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bfb_documentation/',
        'demo'=>'https://bestwpdeveloper.com/flip-box-addon-for-service',
        'video'=>'https://youtu.be/1oOcufI_zVk',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Flip Box Carousel','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-flip-box-carousel',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/flip-box-carousel',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Step Flip Box','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-step-flip-box',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/flip-box-addon-for-step',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Team Flip Box','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-team-flip-box',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/flip-box-addon-for-team',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Map Masking','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-map-masking',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bmm_documentation/',
        'demo'=>'https://bestwpdeveloper.com/bwd-map-masking',
        'video'=>'https://youtu.be/hZqa4C1F2f4',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Creative List','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-creative-list',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bcl_documentation/',
        'demo'=>'https://bestwpdeveloper.com/creative-list-addon-for-elementor',
        'video'=>'https://youtu.be/PrR1zSj3oYE',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Dual Heading','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-dual-heading',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bdh_documentation/',
        'demo'=>'https://bestwpdeveloper.com/dual-heading-addon-for-elementor',
        'video'=>'https://youtu.be/LxJLKn64NTw',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Back To Top','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-back-to-top',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bub_documentation/',
        'demo'=>'https://bestwpdeveloper.com/back-to-top-addon-for-elementor',
        'video'=>'https://youtu.be/KxoIqQMRtaI',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Call To Action','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-call-to-action',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bac_documentation/',
        'demo'=>'https://bestwpdeveloper.com/call-to-action-for-elementor',
        'video'=>'https://youtu.be/vdVkqTTbsj0',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Icon Box','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-icon-box',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bib_documentation/',
        'demo'=>'https://bestwpdeveloper.com/icon-box-addon-for-elementor',
        'video'=>'https://youtu.be/UcZGtXkCxQw',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Dual Button','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-dual-button',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bdb_documentation/',
        'demo'=>'https://bestwpdeveloper.com/dual-button-addon-for-elementor',
        'video'=>'https://youtu.be/vzfV9sg82GA',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Awesome Step','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-awesome-step',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bas_documentation/',
        'demo'=>'https://bestwpdeveloper.com/step-addon-for-elementor',
        'video'=>'https://youtu.be/vgEbdBGmL0I',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Counter','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-counter',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bc_documentation/',
        'demo'=>'https://bestwpdeveloper.com/counter-addon-for-elementor',
        'video'=>'https://youtu.be/rMYs56zi9mU',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Image Hover Effect','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-image-hover-effect',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bihe_documentation/',
        'demo'=>'https://bestwpdeveloper.com/image-hover-effect-addon-for-elementor',
        'video'=>'https://youtu.be/wGzOjBawVks',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Countdown','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-countdown',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bcd_documentation/',
        'demo'=>'https://bestwpdeveloper.com/count-down-addon-for-elementor',
        'video'=>'https://youtu.be/Yq9d0LqljFM',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Animated Heading','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-animated-heading',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bah_documentation/',
        'demo'=>'https://bestwpdeveloper.com/animated-heading',
        'video'=>'https://youtu.be/pAsB3czMJpk',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Filterable Gallery','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-filterable-gallery',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bfg_documentation/',
        'demo'=>'https://bestwpdeveloper.com/filterable-gallery-for-elementor',
        'video'=>'https://youtu.be/mPbbrVy6Peo',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Pricing Table','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-pricing-table',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bpt_documentation/',
        'demo'=>'https://bestwpdeveloper.com/pricing-table-addon-for-elementor',
        'video'=>'https://youtu.be/1TPxbcLMIlg',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Social Icon','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-social-icon',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bsi_documentation/',
        'demo'=>'https://bestwpdeveloper.com/social-icon-addon-for-elementor',
        'video'=>'https://youtu.be/zZBjFeyfMz8',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Creative Tab','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-creative-tab',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/ct_documentation/',
        'demo'=>'https://bestwpdeveloper.com/creative-tabs-addon-for-elementor',
        'video'=>'https://youtu.be/ND7HAJaM540',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Author Bio','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-author-bio',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bab_documentation/',
        'demo'=>'https://bestwpdeveloper.com/author-bio-addon-for-elementor',
        'video'=>'https://youtu.be/n59aK0MVhq0',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Animated Link','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-animated-link',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bal_documentation/',
        'demo'=>'https://bestwpdeveloper.com/animated-link-plugin-for-elementor',
        'video'=>'https://youtu.be/QrRmubDyYO0',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Business Hours','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-business-hours',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bbh_documentation/',
        'demo'=>'https://bestwpdeveloper.com/business-hours-addon-for-elementor',
        'video'=>'https://youtu.be/Dv3o4xeFKt8',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Image Shape','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-image-shape',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bis_documentation/',
        'demo'=>'https://bestwpdeveloper.com/bwd-image-shape',
        'video'=>'https://youtu.be/MXQ2stKp1TM',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Fancy Heading','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-fancy-heading',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bfh_documentation/',
        'demo'=>'https://bestwpdeveloper.com/fancy-heading-addon-for-elementor',
        'video'=>'https://youtu.be/s4vv9k59YIU',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Progress Bar','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-progress-bar',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/pb_documentation/',
        'demo'=>'https://bestwpdeveloper.com/progress-bar-addon-for-elementor',
        'video'=>'https://youtu.be/Nd9-s0LUScY',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Image Accordion','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-image-accordion',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bia_documentation/',
        'demo'=>'https://bestwpdeveloper.com/image-accordion',
        'video'=>'https://youtu.be/0PeOVgMsE8U',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Image Compare','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-image-compare',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bic_documentation/',
        'demo'=>'https://bestwpdeveloper.com/image-compare',
        'video'=>'https://youtu.be/VaHUBjapJo4',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Timeline','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-timeline',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bit_documentation/',
        'demo'=>'https://bestwpdeveloper.com/timeline',
        'video'=>'https://youtu.be/DwUDn5LoHbw',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Blockquote','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-blockquote',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bbq_documentation/',
        'demo'=>'https://bestwpdeveloper.com/blockquote',
        'video'=>'https://youtu.be/9uTAOUmMVIY',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Video Popup','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-video-popup',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bvp_documentation/',
        'demo'=>'https://bestwpdeveloper.com/video-popup',
        'video'=>'https://youtu.be/ux_ccVc4jp0',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Image Stack Group','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-image-stack-group',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/isg_documentation/',
        'demo'=>'https://bestwpdeveloper.com/image-stack-group',
        'video'=>'https://youtu.be/-rFwAjptPNU',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Masking Video','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-masking-video',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bmv_documentation/',
        'demo'=>'https://bestwpdeveloper.com/masking-video-addon-for-elementor',
        'video'=>'https://youtu.be/bKFpRTfJGXU',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Image Swap','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-image-swap',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/is_documentation/',
        'demo'=>'https://bestwpdeveloper.com/image-swap',
        'video'=>'https://youtu.be/Nd7vTs4jf2Y',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Profile Card','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-profile-card',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bpc_documentation/',
        'demo'=>'https://bestwpdeveloper.com/profile-card-addon-for-elementor',
        'video'=>'https://youtu.be/xsL9Y5rKNrA',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Photo Stack','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-photo-stack',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/ps_documentation/',
        'demo'=>'https://bestwpdeveloper.com/photo-stack-plugin-for-elementor-page-builder',
        'video'=>'https://youtu.be/sBGZHB1bh0g',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Image Scroll','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-image-scroll',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/biscrol_documentation/',
        'demo'=>'https://bestwpdeveloper.com/image-scroll-elementor-addon',
        'video'=>'https://youtu.be/DN_QkzBGaYE',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('I Hover','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-ihover',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/ie_documentation/',
        'demo'=>'https://bestwpdeveloper.com/ihover',
        'video'=>'https://youtu.be/bnB-TwipphA',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Webinar Info','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-webinar-info',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bwi_documentation/',
        'demo'=>'https://bestwpdeveloper.com/webinar-info-addon-for-elementor',
        'video'=>'https://youtu.be/BbhoRwCvRLs',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Circle Info','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-circle-info',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/interactive-circle-infographic',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Coupon Code','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-coupon-code',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bcc_documentation/',
        'demo'=>'https://bestwpdeveloper.com/elementor-coupon-code',
        'video'=>'https://youtu.be/NDnhR6mryQk',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Unique Headers','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-unique-headers',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/tuh_documentation/',
        'demo'=>'https://bestwpdeveloper.com/elementor-header',
        'video'=>'https://youtu.be/mzuUEsokwfg',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Click to Contact','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-click-to-contact',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/ctc_documentation/',
        'demo'=>'https://bestwpdeveloper.com/plugins/click-to-contact',
        'video'=>'https://youtu.be/8lIDR4E9eZ0',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Data Table','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-data-table',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/dt_documentation/',
        'demo'=>'https://bestwpdeveloper.com/elementor-data-table',
        'video'=>'https://youtu.be/qWfl8tWiUi4',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Contact Form 7 Styler','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-contact-form-7-styler',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bwdcs_documentation/',
        'demo'=>'https://bestwpdeveloper.com/contact-form-7-styler',
        'video'=>'https://youtu.be/OGbvLL0FYeU',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Logo Carousel','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-logo-carousel',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/brand-logo-carousel',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Logo Grid','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-logo-grid',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/brand-logo-grid',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Logo Filter','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-logo-filter',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/brand-logo-filter',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Team Carousel','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-team-carousel',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/tc_documentation/',
        'demo'=>'https://bestwpdeveloper.com/team-member-carousel',
        'video'=>'https://youtu.be/9pJjXA4WJEo',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Code Highlighter','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-code-highlighter',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/ch_documentation/',
        'demo'=>'https://bestwpdeveloper.com/code-highlighter',
        'video'=>'https://youtu.be/_LiqhtLp-AM',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Breadcrumb','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-breadcrumb',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bb_documentation/',
        'demo'=>'https://bestwpdeveloper.com/breadcrumb',
        'video'=>'https://youtu.be/63LVEmx82kc',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Info Download Button','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-info-download-button',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/indb_documentation/',
        'demo'=>'https://bestwpdeveloper.com/info-download-button',
        'video'=>'https://youtu.be/IonUxHpHkGs',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Effective Pre Loader','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-effective-pre-loader',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bep_documentation/',
        'demo'=>'https://bestwpdeveloper.com/pre-loader',
        'video'=>'https://youtu.be/45ki61ZB-68',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Social Share','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-social-share',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bwdss_documentation/',
        'demo'=>'https://bestwpdeveloper.com/social-share',
        'video'=>'https://youtu.be/6w_cxs-eOgw',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Background Switcher','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-background-switcher',
        'documentation'=>'https://bwdplugins.com/plugins_documentations/bbs_documentation/',
        'demo'=>'https://bestwpdeveloper.com/background-switcher',
        'video'=>'https://youtu.be/Szp42b_C6yE',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Content Switcher','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-content-switcher',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/content-switcher',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    // Free end
    [
        'name'=>esc_html__('Honeycombs','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-honeycombs',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/honeycombs',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Popup Elementor Addon','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-popup',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/popup-elementor-addon',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Advanced Slider','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-advanced-slider',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/advanced-slider',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Anything Slide','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-slide-anything',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/anything-slide',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Image Hotspot','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-image-hotspot',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/image-hotspot',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Unfold Content','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-unfold',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/unfold-content',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Effective Lottie Animation','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-lottie-animation',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/effective-lottie-animation',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Bar Chart','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-bar-chart',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/bar-chart',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Lord Icon','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-lord-icon',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/lord-icon',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Card Flipper Pro','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-cart-flipper',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/card-flipper-pro',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Ajax Data Table','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-ajax-data-table',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/ajax-data-table',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Content Switcher Plus','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-con-swi-pls',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/content-switcher-plus',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Image Reveal Animation','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-img-rev-widg',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/image-reveal-animation',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Image Unfold Kit','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-img-unfold-kit',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/image-unfold-kit',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Modern Feature List','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-modern-feature-list',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/modern-feature-list',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Offcanvas Slide Magic','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-offcanvasmagic',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/offcanvas-slide-magic',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Private Content Locker','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-privacy-content-locker',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/private-content-locker',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Clear PDF View','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-viewpdf',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/clear-pdf-view',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Progress Master Kit','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-progress-master-kit',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/progress-master-kit',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Restaurant Price Menu','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-restaurant-price-menu',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/restaurant-price-menu',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Sales Promotion Offer','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-sales-promotion-offer',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/sales-promotion-offer',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Showcase Your Profile','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-profile-showcas',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/showcase-your-profile',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Tooltip Mastery','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-tooltip-mastery',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/tooltip-mastery',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Employee Profile Identity','bwd-elementor-addons'),
        'id'=>'bwdeb-employee-profile-identity',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/employee-profile-identity',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Horizontal Timeline Slider','bwd-elementor-addons'),
        'id'=>'bwdeb-horizontal-timeline-slider',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/horizontal-timeline-slider',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Showcase Product Features','bwd-elementor-addons'),
        'id'=>'bwdeb-product-features-w',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/Showcase-Product-Features',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('360 Rotation View','bwd-elementor-addons'),
        'id'=>'bwdeb-threesixty-rotation-view',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/threesixty-rotation-view',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('FAQ','bwd-elementor-addons'),
        'id'=>'bwdeb-widget-template',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/bwd-faq',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Pricing Scheme Switcher','bwd-elementor-addons'),
        'id'=>'bwdeb-pssx',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/pricing-scheme-switcher',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Bio About Maker','bwd-elementor-addons'),
        'id'=>'bwdeb-blmx1',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/bio-about-maker',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Bio Link Maker','bwd-elementor-addons'),
        'id'=>'bwdeb-blmx2',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/bio-link-maker',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Bio Social Maker','bwd-elementor-addons'),
        'id'=>'bwdeb-blmx3',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/bio-social-maker',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Sticky Video Prime','bwd-elementor-addons'),
        'id'=>'bwdeb-svpx',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/sticky-video-prime',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Tabify Xpert Suite','bwd-elementor-addons'),
        'id'=>'bwdeb-txsx',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/tabify-xpert-suite',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Vertical Split Slideshow','bwd-elementor-addons'),
        'id'=>'bwdeb-vsix',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/vertical-split-slideshow',
        'video'=>'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ]
];
// ====================================================
// For CV Builder widgets
$cvWidgets = [
    [
        'name' => esc_html__('Builder', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-cv-builder',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bcvb_documentation/',
        'demo' => 'https://bestwpdeveloper.com/cv-builder-plugin-for-elementor/',
        'video' => 'https://youtu.be/EeuQyTVc0Ig',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('About', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-cv-about',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bcvb_documentation/',
        'demo' => 'https://bestwpdeveloper.com/cv-builder-plugin-for-elementor/',
        'video' => 'https://youtu.be/EeuQyTVc0Ig',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Contact', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-cv-contact',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bcvb_documentation/',
        'demo' => 'https://bestwpdeveloper.com/cv-builder-plugin-for-elementor/',
        'video' => 'https://youtu.be/EeuQyTVc0Ig',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Education', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-cv-education',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bcvb_documentation/',
        'demo' => 'https://bestwpdeveloper.com/cv-builder-plugin-for-elementor/',
        'video' => 'https://youtu.be/EeuQyTVc0Ig',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Experience', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-cv-experience',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bcvb_documentation/',
        'demo' => 'https://bestwpdeveloper.com/cv-builder-plugin-for-elementor/',
        'video' => 'https://youtu.be/EeuQyTVc0Ig',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Footer', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-cv-footer',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bcvb_documentation/',
        'demo' => 'https://bestwpdeveloper.com/cv-builder-plugin-for-elementor/',
        'video' => 'https://youtu.be/EeuQyTVc0Ig',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Header', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-cv-header',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bcvb_documentation/',
        'demo' => 'https://bestwpdeveloper.com/cv-builder-plugin-for-elementor/',
        'video' => 'https://youtu.be/EeuQyTVc0Ig',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Hobby', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-cv-hobby',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bcvb_documentation/',
        'demo' => 'https://bestwpdeveloper.com/cv-builder-plugin-for-elementor/',
        'video' => 'https://youtu.be/EeuQyTVc0Ig',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Language', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-cv-language',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bcvb_documentation/',
        'demo' => 'https://bestwpdeveloper.com/cv-builder-plugin-for-elementor/',
        'video' => 'https://youtu.be/EeuQyTVc0Ig',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Reference', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-cv-reference',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bcvb_documentation/',
        'demo' => 'https://bestwpdeveloper.com/cv-builder-plugin-for-elementor/',
        'video' => 'https://youtu.be/EeuQyTVc0Ig',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Skill', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-cv-skill',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bcvb_documentation/',
        'demo' => 'https://bestwpdeveloper.com/cv-builder-plugin-for-elementor/',
        'video' => 'https://youtu.be/EeuQyTVc0Ig',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ]
];
// ====================================================
// For hero section
$heroWidgets = array();
for ($i = 1; $i <= 13; $i++) {
    $heroWidgets[] = array('id' => 'bwdeb-check-hero-widget' . $i);
}
// ====================================================
// For blogs widgets
$postWidgets = [
    [
        'name' => esc_html__('Post Grid', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-post-grid',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bpg_documentation/',
        'demo' => 'https://bestwpdeveloper.com/post-grid-elementor-addon',
        'video' => 'https://youtu.be/yTS8QLQ21Wc',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Post List', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-post-list',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bpl_documentation/',
        'demo' => 'https://bestwpdeveloper.com/blog-post-list',
        'video' => 'https://youtu.be/U4mNqSR7BnM',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Post Tiles', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-post-tiles',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/pt_documentation/',
        'demo' => 'https://bestwpdeveloper.com/post-tiles',
        'video' => 'https://youtu.be/vInzwBMk-8g',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Post Accordion', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-post-accordion',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bpa_documentation/',
        'demo' => 'https://bestwpdeveloper.com/blog-post-accordions',
        'video' => 'https://youtu.be/zEQX5bs-ixA',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Post Timeline', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-post-timeline',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bwdpt_documentation/',
        'demo' => 'https://bestwpdeveloper.com/post-timeline',
        'video' => 'https://youtu.be/uG-zfqFMp5Q',
        'free_pro' => true,
        'new' => true,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Masonry Blog Post', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-masonary-blog-post',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/mbp_documentation/',
        'demo' => 'https://bestwpdeveloper.com/masonry-blog-post',
        'video' => 'https://youtu.be/9gZO7VJDX_s',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Post Image Accordion', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-post-image-accordion',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bpia_documentation/',
        'demo' => 'https://bestwpdeveloper.com/post-image-accordion',
        'video' => 'https://youtu.be/b1akfGvkAjU',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Single Post Slider', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-single-post-slider',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/effective-post-slider',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('News Ticker', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-news-ticker',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/nt_documentation/',
        'demo' => 'https://bestwpdeveloper.com/news-ticker/',
        'video' => 'https://youtu.be/wYAgOsXuAGo',
        'free_pro' => true,
        'new' => true,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Creative Post Carousel', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-creative-post-carousel',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bwdpc_documentation/',
        'demo' => 'https://bestwpdeveloper.com/post-carousel',
        'video' => 'https://youtu.be/0JlzpM3vY68',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Post Prestige Portfolio', 'bwd-elementor-addons'),
        'id' => 'bwdeb-post-prestige-portfolio',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => true,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Advanced Posts Tab', 'bwd-elementor-addons'),
        'id' => 'bwdeb-apostst',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ]
];
// ====================================================
// For woocommerce widgets
$productWidgets = [
    [
        'name' => esc_html__('Product Grid', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-product-grid',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/bcpg_documentation/',
        'demo' => 'https://bestwpdeveloper.com/woocommerce-product-grid-addon-for-elementor',
        'video' => 'https://youtu.be/o5gMNFCSfFk',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Product List', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-product-list',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/wcpl_documentation/',
        'demo' => 'https://bestwpdeveloper.com/creative-products-list',
        'video' => 'https://youtu.be/pTYzZmbgr6g',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Product Tiles', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-product-tiles',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/wpt_documentation/',
        'demo' => 'https://bestwpdeveloper.com/product-tiles',
        'video' => 'https://youtu.be/ODg6BasPxc0',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Product Carousel', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-product-carousel',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/gpc_documentation/',
        'demo' => 'https://bestwpdeveloper.com/product-carousel',
        'video' => 'https://youtu.be/keVdF2gEiok',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Product Category Grid', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-product-category-grid',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/pcg_documentation/',
        'demo' => 'https://bestwpdeveloper.com/woocommerce-product-category-grid',
        'video' => 'https://youtu.be/5k5UWXw85ec',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Product Category Tiles', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-product-category-tiles',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/wpct_documentation/',
        'demo' => 'https://bestwpdeveloper.com/woocommerce-product-category-tiles',
        'video' => 'https://youtu.be/HN317B4tSoI',
        'free_pro' => true,
        'new' => true,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Product Accordion', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-product-accordion',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/wpa_documentation/',
        'demo' => 'https://bestwpdeveloper.com/product-accordion',
        'video' => 'https://youtu.be/zFz98rgw0sI',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Product Image Accordion', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-product-image-accordion',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/wpia_documentation/',
        'demo' => 'https://bestwpdeveloper.com/product-image-accordion',
        'video' => 'https://youtu.be/z8vXk1oo1HQ',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Product List Carousel', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-product-list-carousel',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/plc_documentation/',
        'demo' => 'https://bestwpdeveloper.com/creative-product-list-carousel',
        'video' => 'https://youtu.be/jKLkSQt6fC4',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Product Timeline', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-product-timeline',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/woopt_documentation/',
        'demo' => 'https://bestwpdeveloper.com/product-timeline',
        'video' => 'https://youtu.be/dnjtTbxsxk0',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Related Product', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-related-product',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/wrp_documentation/',
        'demo' => 'https://bestwpdeveloper.com/woocommerce-related-product',
        'video' => 'https://youtu.be/4EmvvXsxDk8',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Product Category Carousel', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-product-category-carousel',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/pcc_documentation/',
        'demo' => 'https://bestwpdeveloper.com/product-category-carousel',
        'video' => 'https://youtu.be/I6OlS6LPdxc',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Featured Product', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-featured-product',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/wfpg_documentation/',
        'demo' => 'https://bestwpdeveloper.com/featured-product',
        'video' => 'https://youtu.be/O2ti4GlDUzY',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Product Compare', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-product-compare',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => true,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Category Gallery', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-woo-cat-gallery',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/wcg_documentation/',
        'demo' => 'https://bestwpdeveloper.com/',
        'video' => 'https://youtu.be/_VVKmrtnQZc',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Product Multi Action', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-woop-multi-action',
        'documentation' => 'https://bwdplugins.com/plugins_documentations/wpma_documentation/',
        'demo' => 'https://bestwpdeveloper.com/',
        'video' => 'https://youtu.be/fHpoRcb1jVI',
        'free_pro' => false,
        'new' => true,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Product Wish Action', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-woop-wish-cont',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => true,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Product Vendors', 'bwd-elementor-addons'),
        'id' => 'bwdeb-woop-vendors',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => true,
        'used' => 0,
    ],
    [
        'name' => esc_html__('3D Product Layout', 'bwd-elementor-addons'),
        'id' => 'bwdeb-twpx',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => true,
        'used' => 0,
    ]
];
// ====================================================
// For extensions 
$extentionsWidgets = [
    [
        'name' => esc_html__('Text Tooltip', 'bwd-elementor-addons'),
        'id' => 'bwdeb-extn-tooltip',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Wrap Link', 'bwd-elementor-addons'),
        'id' => 'bwdeb-extn-link',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Content Protection', 'bwd-elementor-addons'),
        'id' => 'bwdeb-extn-protctn',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('CSS Transform', 'bwd-elementor-addons'),
        'id' => 'bwdeb-csstrnsm',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Floating Animation', 'bwd-elementor-addons'),
        'id' => 'bwdeb-flanime',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('3D Text', 'bwd-elementor-addons'),
        'id' => 'bwdeb-3d-text',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Notation', 'bwd-elementor-addons'),
        'id' => 'bwdeb-notation',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Confetti Effects', 'bwd-elementor-addons'),
        'id' => 'bwdeb-confetti-effects',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Cursor Effects', 'bwd-elementor-addons'),
        'id' => 'bwdeb-cursor-effects',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Reveal Effects', 'bwd-elementor-addons'),
        'id' => 'bwdeb-reveal-effects',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Tile Scroll', 'bwd-elementor-addons'),
        'id' => 'bwdeb-tile-scroll',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Section Sticky', 'bwd-elementor-addons'),
        'id' => 'bwdeb-section-sticky',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Scroll Box', 'bwd-elementor-addons'),
        'id' => 'bwdeb-scroll-box',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Background Particles', 'bwd-elementor-addons'),
        'id' => 'bwdeb-background-particles',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Cross Domain', 'bwd-elementor-addons'),
        'id' => 'bwdeb-xd-copy',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Custom JS & CSS', 'bwd-elementor-addons'),
        'id' => 'bwdeb-custom-jscss',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Background Parallax', 'bwd-elementor-addons'),
        'id' => 'bwdeb-section-parallax',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Gradient Animated Background', 'bwd-elementor-addons'),
        'id' => 'bwdeb-gra-anim-bg',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Backdrop Filter', 'bwd-elementor-addons'),
        'id' => 'bwdeb-backdrop-filter',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Line Grid', 'bwd-elementor-addons'),
        'id' => 'bwdeb-line-grid',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Cursor Image Parallax', 'bwd-elementor-addons'),
        'id' => 'bwdeb-cursor-img-parallax',
        'documentation' => 'https://bestwpdeveloper.com/documentation/',
        'demo' => 'https://bestwpdeveloper.com/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ]
];
// For extra settings
$extraStng = [
    [
        'name' => esc_html__('Duplicate', 'bwd-elementor-addons'),
        'id' => 'bwdeb-duplicate',
        'logo' => '../../assets/admin/dashboard/images/asset.svg',
        'description' => esc_html__('Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.', 'bwd-elementor-addons'),
        'demo' => 'https://bestwpdeveloper.com/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Live Copy', 'bwd-elementor-addons'),
        'id' => 'bwdeb-live-copy',
        'logo' => '../../assets/admin/dashboard/images/asset.svg',
        'description' => esc_html__('Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.', 'bwd-elementor-addons'),
        'demo' => 'https://bestwpdeveloper.com/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Custom JS & CSS', 'bwd-elementor-addons'),
        'id' => 'bwdeb-custom-jscss',
        'logo' => '../../assets/admin/dashboard/images/asset.svg',
        'description' => esc_html__('Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.', 'bwd-elementor-addons'),
        'demo' => 'https://bestwpdeveloper.com/',
        'video' => 'https://www.youtube.com/@bestwpdeveloper2605',
        'free_pro' => false,
        'new' => false,
    ]
];
// For license
$getLicense = [
    [
        'id'=>'feature-one',
        'name'=>esc_html__('All Widgets & Presets','bwd-elementor-addons'),
        'free'=>true,
        'pro'=>true,
    ],
    [
        'id'=>'feature-two',
        'name'=>esc_html__('Two Presets all of Free/Pro Widgets','bwd-elementor-addons'),
        'free'=>false,
        'pro'=>true,
    ],
    [
        'id'=>'feature-two',
        'name'=>esc_html__('Extensions','bwd-elementor-addons'),
        'free'=>true,
        'pro'=>true,
    ],
    [
        'id'=>'feature-three',
        'name'=>esc_html__('Integrations','bwd-elementor-addons'),
        'free'=>true,
        'pro'=>true,
    ],
    [
        'id'=>'feature-four',
        'name'=>esc_html__('Extra Settings','bwd-elementor-addons'),
        'free'=>true,
        'pro'=>true,
    ],
    [
        'id'=>'feature-five',
        'name'=>esc_html__('Effects','bwd-elementor-addons'),
        'free'=>false,
        'pro'=>true,
    ]
];
