<?php
/**
 * 
 * @admin ~~// this is the file for all arrays
 * 
 */
if ( ! defined( 'ABSPATH' ) ) exit;
// Live Copy,Vertical Split Slideshow,Advanced Posts Tab,Product Vendors,Reveal Effects
// ====================================================
// For new show
$whatsNew = [
    [
        'img'=>'../../assets/admin/dashboard/images/small-logo.png',
        'name'=>esc_html__('Live Copy','bwd-elementor-addons'),
        'desc'=>esc_html__('Copy-paste Elementor designs across sites easily.','bwd-elementor-addons'),
    ],
    [
        'img'=>'../../assets/admin/dashboard/images/small-logo.png',
        'name'=>esc_html__('Vertical Split Slideshow','bwd-elementor-addons'),
        'desc'=>esc_html__('Create vertical split-screen image slideshows.','bwd-elementor-addons'),
    ],
    [
        'img'=>'../../assets/admin/dashboard/images/small-logo.png',
        'name'=>esc_html__('Advanced Posts Tab','bwd-elementor-addons'),
        'desc'=>esc_html__('Display posts in tabbed, organized layout.','bwd-elementor-addons'),
    ],
    [
        'img'=>'../../assets/admin/dashboard/images/small-logo.png',
        'name'=>esc_html__('Product Vendors','bwd-elementor-addons'),
        'desc'=>esc_html__('Manage and showcase multiple product vendors.','bwd-elementor-addons'),
    ],
    [
        'img'=>'../../assets/admin/dashboard/images/small-logo.png',
        'name'=>esc_html__('Reveal Effects','bwd-elementor-addons'),
        'desc'=>esc_html__('Add animated reveal effects to elements.','bwd-elementor-addons'),
    ]
];
// ====================================================
// For general
$generalWidgets = [
    [
        'name'=>esc_html__('Meet The Team','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-meet-the-team',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/meet-the-team',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>1,
    ],
    [
        'name'=>esc_html__('Testimonials','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-testimonials',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/testimonial-addon-for-elementor',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>2,
    ],
    [
        'name'=>esc_html__('Creative Button','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-creative-button',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/creative-button',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>3,
    ],
    [
        'name'=>esc_html__('Accordion','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-accordion',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/accordion-addon-for-elementor',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Masking Effect','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-masking-effect',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/bwd-masking-effect',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Service Showcase','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-service-showcase',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/service-addon-for-elementor',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Promo Box','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-promo-box',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/promo-box',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Service Flip Box','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-service-flip-box',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/flip-box-addon-for-service',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Flip Box Carousel','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-flip-box-carousel',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/flip-box-carousel',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Step Flip Box','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-step-flip-box',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/flip-box-addon-for-step',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Team Flip Box','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-team-flip-box',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/flip-box-addon-for-team',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Map Masking','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-map-masking',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/bwd-map-masking',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Creative List','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-creative-list',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/creative-list-addon-for-elementor',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Dual Heading','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-dual-heading',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/dual-heading-addon-for-elementor',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Back To Top','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-back-to-top',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/back-to-top-addon-for-elementor',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Call To Action','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-call-to-action',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/call-to-action-for-elementor',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Icon Box','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-icon-box',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/icon-box-addon-for-elementor',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Dual Button','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-dual-button',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/dual-button-addon-for-elementor',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Awesome Step','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-awesome-step',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/step-addon-for-elementor',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Counter','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-counter',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/counter-addon-for-elementor',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Image Hover Effect','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-image-hover-effect',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/image-hover-effect-addon-for-elementor',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Countdown','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-countdown',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/count-down-addon-for-elementor',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Animated Heading','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-animated-heading',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/animated-heading',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Filterable Gallery','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-filterable-gallery',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/filterable-gallery-for-elementor',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Pricing Table','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-pricing-table',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/pricing-table-addon-for-elementor',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Social Icon','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-social-icon',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/social-icon-addon-for-elementor',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Creative Tab','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-creative-tab',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/creative-tabs-addon-for-elementor',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Author Bio','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-author-bio',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/author-bio-addon-for-elementor',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Animated Link','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-animated-link',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/animated-link-plugin-for-elementor',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Business Hours','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-business-hours',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/business-hours-addon-for-elementor',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Image Shape','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-image-shape',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/bwd-image-shape',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Fancy Heading','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-fancy-heading',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/fancy-heading-addon-for-elementor',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Progress Bar','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-progress-bar',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/progress-bar-addon-for-elementor',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Image Accordion','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-image-accordion',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/image-accordion',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Image Compare','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-image-compare',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/image-compare',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Timeline','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-timeline',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/timeline',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Blockquote','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-blockquote',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/blockquote',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Video Popup','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-video-popup',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/video-popup',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Image Stack Group','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-image-stack-group',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/image-stack-group',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Masking Video','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-masking-video',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/masking-video-addon-for-elementor',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Image Swap','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-image-swap',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/image-swap',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Profile Card','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-profile-card',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/profile-card-addon-for-elementor',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Photo Stack','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-photo-stack',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/photo-stack-plugin-for-elementor-page-builder',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Image Scroll','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-image-scroll',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/image-scroll-elementor-addon',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('I Hover','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-ihover',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/ihover',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Webinar Info','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-webinar-info',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/webinar-info-addon-for-elementor',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Circle Info','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-circle-info',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/interactive-circle-infographic',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Coupon Code','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-coupon-code',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/elementor-coupon-code',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Unique Headers','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-unique-headers',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/elementor-header',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Click to Contact','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-click-to-contact',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/plugins/click-to-contact',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Data Table','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-data-table',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/elementor-data-table',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Contact Form 7 Styler','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-contact-form-7-styler',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/contact-form-7-styler',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Logo Carousel','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-logo-carousel',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/brand-logo-carousel',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Logo Grid','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-logo-grid',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/brand-logo-grid',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Logo Filter','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-logo-filter',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/brand-logo-filter',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Team Carousel','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-team-carousel',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/team-member-carousel',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Code Highlighter','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-code-highlighter',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/code-highlighter',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Breadcrumb','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-breadcrumb',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/breadcrumb',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Info Download Button','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-info-download-button',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/info-download-button',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Effective Pre Loader','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-effective-pre-loader',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/pre-loader',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Social Share','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-social-share',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/social-share',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Background Switcher','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-background-switcher',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/background-switcher',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    [
        'name'=>esc_html__('Content Switcher','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-content-switcher',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/content-switcher',
        'video'=>'youtube.com',
        'free_pro'=>true,
        'new'=>false,
        'used'=>0
    ],
    // Free end
    [
        'name'=>esc_html__('Honeycombs','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-honeycombs',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/honeycombs',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Popup Elementor Addon','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-popup',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/popup-elementor-addon',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Advanced Slider','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-advanced-slider',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/advanced-slider',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Anything Slide','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-slide-anything',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/anything-slide',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Image Hotspot','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-image-hotspot',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/image-hotspot',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Unfold Content','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-unfold',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/unfold-content',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Effective Lottie Animation','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-lottie-animation',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/effective-lottie-animation',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Bar Chart','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-bar-chart',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/bar-chart',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Lord Icon','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-lord-icon',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/lord-icon',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Card Flipper Pro','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-cart-flipper',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/card-flipper-pro',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Ajax Data Table','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-ajax-data-table',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/ajax-data-table',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Content Switcher Plus','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-con-swi-pls',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/content-switcher-plus',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Image Reveal Animation','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-img-rev-widg',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/image-reveal-animation',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Image Unfold Kit','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-img-unfold-kit',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/image-unfold-kit',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Modern Feature List','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-modern-feature-list',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/modern-feature-list',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Offcanvas Slide Magic','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-offcanvasmagic',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/offcanvas-slide-magic',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Private Content Locker','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-privacy-content-locker',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/private-content-locker',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Clear PDF View','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-viewpdf',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/clear-pdf-view',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Progress Master Kit','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-progress-master-kit',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/progress-master-kit',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Restaurant Price Menu','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-restaurant-price-menu',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/restaurant-price-menu',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Sales Promotion Offer','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-sales-promotion-offer',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/sales-promotion-offer',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Showcase Your Profile','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-profile-showcas',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/showcase-your-profile',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Tooltip Mastery','bwd-elementor-addons'),
        'id'=>'bwdeb-plugin-tooltip-mastery',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/tooltip-mastery',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Employee Profile Identity','bwd-elementor-addons'),
        'id'=>'bwdeb-employee-profile-identity',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/employee-profile-identity',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Horizontal Timeline Slider','bwd-elementor-addons'),
        'id'=>'bwdeb-horizontal-timeline-slider',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/horizontal-timeline-slider',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Showcase Product Features','bwd-elementor-addons'),
        'id'=>'bwdeb-product-features-w',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/Showcase-Product-Features',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('360 Rotation View','bwd-elementor-addons'),
        'id'=>'bwdeb-threesixty-rotation-view',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/threesixty-rotation-view',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('FAQ','bwd-elementor-addons'),
        'id'=>'bwdeb-widget-template',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/bwd-faq',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Pricing Scheme Switcher','bwd-elementor-addons'),
        'id'=>'bwdeb-pssx',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/pricing-scheme-switcher',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Bio About Maker','bwd-elementor-addons'),
        'id'=>'bwdeb-blmx1',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/bio-about-maker',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Bio Link Maker','bwd-elementor-addons'),
        'id'=>'bwdeb-blmx2',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/bio-link-maker',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Bio Social Maker','bwd-elementor-addons'),
        'id'=>'bwdeb-blmx3',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/bio-social-maker',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Sticky Video Prime','bwd-elementor-addons'),
        'id'=>'bwdeb-svpx',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/sticky-video-prime',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Tabify Xpert Suite','bwd-elementor-addons'),
        'id'=>'bwdeb-txsx',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/tabify-xpert-suite',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ],
    [
        'name'=>esc_html__('Vertical Split Slideshow','bwd-elementor-addons'),
        'id'=>'bwdeb-vsix',
        'documentation'=>'https://bestwpdeveloper.com/documentation',
        'demo'=>'https://bestwpdeveloper.com/vertical-split-slideshow',
        'video'=>'youtube.com',
        'free_pro'=>false,
        'new'=>false,
        'used'=>0,
    ]
];
// ====================================================
// For CV Builder widgets
$cvWidgets = [
    [
        'name' => esc_html__('Builder', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-cv-builder',
        'documentation' => '',
        'demo' => 'builder',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('About', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-cv-about',
        'documentation' => '',
        'demo' => 'about',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Contact', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-cv-contact',
        'documentation' => '',
        'demo' => 'contact',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Education', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-cv-education',
        'documentation' => '',
        'demo' => 'education',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Experience', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-cv-experience',
        'documentation' => '',
        'demo' => 'experience',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Footer', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-cv-footer',
        'documentation' => '',
        'demo' => 'footer',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Header', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-cv-header',
        'documentation' => '',
        'demo' => 'header',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Hobby', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-cv-hobby',
        'documentation' => '',
        'demo' => 'hobby',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Language', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-cv-language',
        'documentation' => '',
        'demo' => 'language',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Reference', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-cv-reference',
        'documentation' => '',
        'demo' => 'reference',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Skill', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-cv-skill',
        'documentation' => '',
        'demo' => 'skill',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ]
];
// ====================================================
// For hero section
$heroWidgets = array();
for ($i = 1; $i <= 13; $i++) {
    $heroWidgets[] = array('id' => 'bwdeb-check-hero-widget' . $i);
}
// ====================================================
// For blogs widgets
$postWidgets = [
    [
        'name' => esc_html__('Post Grid', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-post-grid',
        'documentation' => '',
        'demo' => 'post-grid-elementor-addon',
        'video' => 'youtube.com',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Post List', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-post-list',
        'documentation' => '',
        'demo' => 'blog-post-list',
        'video' => 'youtube.com',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Post Tiles', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-post-tiles',
        'documentation' => '',
        'demo' => 'post-tiles',
        'video' => 'youtube.com',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Post Accordion', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-post-accordion',
        'documentation' => '',
        'demo' => 'blog-post-accordions',
        'video' => 'youtube.com',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Post Timeline', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-post-timeline',
        'documentation' => '',
        'demo' => 'post-timeline',
        'video' => 'youtube.com',
        'free_pro' => true,
        'new' => true,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Masonry Blog Post', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-masonary-blog-post',
        'documentation' => '',
        'demo' => 'masonry-blog-post',
        'video' => 'youtube.com',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Post Image Accordion', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-post-image-accordion',
        'documentation' => '',
        'demo' => 'post-image-accordion',
        'video' => 'youtube.com',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Single Post Slider', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-single-post-slider',
        'documentation' => '',
        'demo' => 'effective-post-slider',
        'video' => 'youtube.com',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('News Ticker', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-news-ticker',
        'documentation' => '',
        'demo' => 'news-ticker',
        'video' => 'youtube.com',
        'free_pro' => true,
        'new' => true,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Creative Post Carousel', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-creative-post-carousel',
        'documentation' => '',
        'demo' => 'post-carousel',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Post Prestige Portfolio', 'bwd-elementor-addons'),
        'id' => 'bwdeb-post-prestige-portfolio',
        'documentation' => '',
        'demo' => 'post-prestige-portfolio',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => true,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Advanced Posts Tab', 'bwd-elementor-addons'),
        'id' => 'bwdeb-apostst',
        'documentation' => '',
        'demo' => 'advanced-posts-tab',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ]
];
// ====================================================
// For woocommerce widgets
$productWidgets = [
    [
        'name' => esc_html__('Product Grid', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-product-grid',
        'documentation' => '',
        'demo' => 'woocommerce-product-grid-addon-for-elementor',
        'video' => 'youtube.com',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Product List', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-product-list',
        'documentation' => '',
        'demo' => 'creative-products-list',
        'video' => 'youtube.com',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Product Tiles', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-product-tiles',
        'documentation' => '',
        'demo' => 'product-tiles',
        'video' => 'youtube.com',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Product Carousel', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-product-carousel',
        'documentation' => '',
        'demo' => 'product-carousel',
        'video' => 'youtube.com',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Product Category Grid', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-product-category-grid',
        'documentation' => '',
        'demo' => 'woocommerce-product-category-grid',
        'video' => 'youtube.com',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Product Category Tiles', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-product-category-tiles',
        'documentation' => '',
        'demo' => 'woocommerce-product-category-tiles',
        'video' => 'youtube.com',
        'free_pro' => true,
        'new' => true,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Product Accordion', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-product-accordion',
        'documentation' => '',
        'demo' => 'product-accordion',
        'video' => 'youtube.com',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Product Image Accordion', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-product-image-accordion',
        'documentation' => '',
        'demo' => 'product-image-accordion',
        'video' => 'youtube.com',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Product List Carousel', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-product-list-carousel',
        'documentation' => '',
        'demo' => 'creative-product-list-carousel',
        'video' => 'youtube.com',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Product Timeline', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-product-timeline',
        'documentation' => '',
        'demo' => 'product-timeline',
        'video' => 'youtube.com',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Related Product', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-related-product',
        'documentation' => '',
        'demo' => 'woocommerce-related-product',
        'video' => 'youtube.com',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Product Category Carousel', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-product-category-carousel',
        'documentation' => '',
        'demo' => 'product-category-carousel',
        'video' => 'youtube.com',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Featured Product', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-featured-product',
        'documentation' => '',
        'demo' => 'featured-product',
        'video' => 'youtube.com',
        'free_pro' => true,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Product Compare', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-product-compare',
        'documentation' => '',
        'demo' => 'woocommerce-product-compare',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => true,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Category Gallery', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-woo-cat-gallery',
        'documentation' => '',
        'demo' => 'woocommerce-category-gallery',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Product Multi Action', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-woop-multi-action',
        'documentation' => '',
        'demo' => 'wooCommerce-product-multi-action',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => true,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Product Wish Action', 'bwd-elementor-addons'),
        'id' => 'bwdeb-plugin-woop-wish-cont',
        'documentation' => '',
        'demo' => 'wooCommerce-product-wish-action',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => true,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Product Vendors', 'bwd-elementor-addons'),
        'id' => 'bwdeb-woop-vendors',
        'documentation' => '',
        'demo' => 'woocommerce-product-vendors',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => true,
        'used' => 0,
    ],
    [
        'name' => esc_html__('3D Product Layout', 'bwd-elementor-addons'),
        'id' => 'bwdeb-twpx',
        'documentation' => '',
        'demo' => '3d-woocommerce-product-layout',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => true,
        'used' => 0,
    ]
];
// ====================================================
// For extensions 
$extentionsWidgets = [
    [
        'name' => esc_html__('Text Tooltip', 'bwd-elementor-addons'),
        'id' => 'bwdeb-extn-tooltip',
        'documentation' => '',
        'demo' => 'text-tooltip',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Wrap Link', 'bwd-elementor-addons'),
        'id' => 'bwdeb-extn-link',
        'documentation' => '',
        'demo' => 'wrap-link',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Content Protection', 'bwd-elementor-addons'),
        'id' => 'bwdeb-extn-protctn',
        'documentation' => '',
        'demo' => 'Content-Protection',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('CSS Transform', 'bwd-elementor-addons'),
        'id' => 'bwdeb-csstrnsm',
        'documentation' => '',
        'demo' => 'CSS-Transform',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Floating Animation', 'bwd-elementor-addons'),
        'id' => 'bwdeb-flanime',
        'documentation' => '',
        'demo' => 'Floating-Animation',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('3D Text', 'bwd-elementor-addons'),
        'id' => 'bwdeb-3d-text',
        'documentation' => '',
        'demo' => '3D-Text',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Notation', 'bwd-elementor-addons'),
        'id' => 'bwdeb-notation',
        'documentation' => '',
        'demo' => 'notation',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Confetti Effects', 'bwd-elementor-addons'),
        'id' => 'bwdeb-confetti-effects',
        'documentation' => '',
        'demo' => 'confetti-effects',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Cursor Effects', 'bwd-elementor-addons'),
        'id' => 'bwdeb-cursor-effects',
        'documentation' => '',
        'demo' => 'cursor-effects',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Reveal Effects', 'bwd-elementor-addons'),
        'id' => 'bwdeb-reveal-effects',
        'documentation' => '',
        'demo' => 'reveal-effects',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Tile Scroll', 'bwd-elementor-addons'),
        'id' => 'bwdeb-tile-scroll',
        'documentation' => '',
        'demo' => 'tile-scroll',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Section Sticky', 'bwd-elementor-addons'),
        'id' => 'bwdeb-section-sticky',
        'documentation' => '',
        'demo' => 'section-sticky',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Scroll Box', 'bwd-elementor-addons'),
        'id' => 'bwdeb-scroll-box',
        'documentation' => '',
        'demo' => 'scroll-box',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Background Particles', 'bwd-elementor-addons'),
        'id' => 'bwdeb-background-particles',
        'documentation' => '',
        'demo' => 'background-particles',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Cross Domain', 'bwd-elementor-addons'),
        'id' => 'bwdeb-xd-copy',
        'documentation' => '',
        'demo' => 'Cross-Domain',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Custom JS & CSS', 'bwd-elementor-addons'),
        'id' => 'bwdeb-custom-jscss',
        'documentation' => '',
        'demo' => 'custom-JS-&-CSS',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Background Parallax', 'bwd-elementor-addons'),
        'id' => 'bwdeb-section-parallax',
        'documentation' => '',
        'demo' => 'background-parallax',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Gradient Animated Background', 'bwd-elementor-addons'),
        'id' => 'bwdeb-gra-anim-bg',
        'documentation' => '',
        'demo' => 'gradiant-animated-BG',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Backdrop Filter', 'bwd-elementor-addons'),
        'id' => 'bwdeb-backdrop-filter',
        'documentation' => '',
        'demo' => 'backdrop-filter',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Line Grid', 'bwd-elementor-addons'),
        'id' => 'bwdeb-line-grid',
        'documentation' => '',
        'demo' => 'line-grid',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ],
    [
        'name' => esc_html__('Cursor Image Parallax', 'bwd-elementor-addons'),
        'id' => 'bwdeb-cursor-img-parallax',
        'documentation' => '',
        'demo' => 'cursor-img-parallax',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
        'used' => 0,
    ]
];
// For extra settings
$extraStng = [
    [
        'name' => esc_html__('Duplicate', 'bwd-elementor-addons'),
        'id' => 'bwdeb-duplicate',
        'logo' => '../../assets/admin/dashboard/images/asset.svg',
        'description' => esc_html__('Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.', 'bwd-elementor-addons'),
        'demo' => 'duplicate',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Live Copy', 'bwd-elementor-addons'),
        'id' => 'bwdeb-live-copy',
        'logo' => '../../assets/admin/dashboard/images/asset.svg',
        'description' => esc_html__('Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.', 'bwd-elementor-addons'),
        'demo' => 'live-copy',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
    ],
    [
        'name' => esc_html__('Custom JS & CSS', 'bwd-elementor-addons'),
        'id' => 'bwdeb-custom-jscss',
        'logo' => '../../assets/admin/dashboard/images/asset.svg',
        'description' => esc_html__('Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.', 'bwd-elementor-addons'),
        'demo' => 'custom-JS-&-CSS',
        'video' => 'youtube.com',
        'free_pro' => false,
        'new' => false,
    ]
];
// For license
$getLicense = [
    [
        'id'=>'feature-one',
        'name'=>esc_html__('All Widgets & Presets','bwd-elementor-addons'),
        'free'=>true,
        'pro'=>true,
    ],
    [
        'id'=>'feature-two',
        'name'=>esc_html__('Two Presets all of Free/Pro Widgets','bwd-elementor-addons'),
        'free'=>false,
        'pro'=>true,
    ],
    [
        'id'=>'feature-two',
        'name'=>esc_html__('Extensions','bwd-elementor-addons'),
        'free'=>true,
        'pro'=>true,
    ],
    [
        'id'=>'feature-three',
        'name'=>esc_html__('Integrations','bwd-elementor-addons'),
        'free'=>true,
        'pro'=>true,
    ],
    [
        'id'=>'feature-four',
        'name'=>esc_html__('Extra Settings','bwd-elementor-addons'),
        'free'=>true,
        'pro'=>true,
    ],
    [
        'id'=>'feature-five',
        'name'=>esc_html__('Effects','bwd-elementor-addons'),
        'free'=>false,
        'pro'=>true,
    ]
];
