<?php
/**
 * 
 * @admin ~~// this is the dashboard widgets tab
 * 
 */
if ( ! defined( 'ABSPATH' ) ) exit;
echo '<div id="widgets" class="bwd-admin-setting-tab">';
		echo '<div class="bwd-widgets-actions-container">';
			echo '<div class="bwd-widgets-en-di-button">';
				echo '<button class="bwd-enable-all bwd-widget-enable-all">Enable All</button>';
				echo '<button class="bwd-disable-all bwd-widget-disable-all">Disable All</button>';
			echo '</div>';
			echo '<div class="bwd-widgets-filter-button-wrap">';
				echo '<div class="bwd-widgets-filter-by">';
					echo '<img src="'.esc_url(plugin_dir_url( __FILE__ ).'../../assets/admin/dashboard/images/Filter.svg').'" alt="">';
					echo '<span>Filter By</span>';
				echo '</div>';
				echo '<button class="bwd-all-widgets-button">all</button>';
				echo '<button class="bwd-free-widgets-button">free</button>';
				echo '<button class="bwd-pro-widgets-button">Pro</button>';
			echo '</div>';
			echo '<div class="bwd-widgets-use-unuse-button">';
				echo '<button class="bwd-widgets-use-button">used<span>0</span></button>';
				echo '<button class="bwd-widgets-unuse-button">unused<span>70</span></button>';
				echo '<div class="bwd-widgets-filter-search">';
					echo '<input type="search" name="" id="search-input" placeholder="Search Widgets">';
					echo '<img class="bwd-widgets-filter-search-icon" src="'.esc_url(plugin_dir_url( __FILE__ ).'../../assets/admin/dashboard/images/search.svg').'" alt="">';
				echo '</div>';
			echo '</div>';
		echo '</div>';
		echo '<div class="bwd-widgets-area-container">';
			echo '<div class="bwd-widgets-items bwd-sk-wrapper">';
                echo $all_T[0];
				echo '<div class="bwd-widgets-item-container bwd-grid">';
                foreach($generalWidgets as $key=>$generalWidget):
					echo '<div class="bwd-sk-cmn bwd-col-xl-3 col-search">';
						echo '<div class="bwd-widgets-item-wrap">';
                        echo $generalWidget['new']==true?'<div class="bwd-widget-new-badge">New</div>':'';
                        $freeProText = $generalWidget['free_pro']==true?esc_html__('Free/Pro','bwd-elementor-addons'):esc_html__('Pro','bwd-elementor-addons');
                        $ifPro = $generalWidget['free_pro']==true?esc_attr('free-'):'';
							echo '<div class="bwd-widget-'.$ifPro.'pro-badge">'.$freeProText.'</div>';
							echo '<div class="bwd-widgets-title-icon-wrap">';
								echo '<div class="bwd-widgets-title">';
									echo '<h6>'.$generalWidget['name'].'</h6>';
									echo '<span>Total used - 0</span>';
								echo '</div>';
								echo '<div class="bwd-widgets-info-icons">';
									echo '<span class="bwd-widgets-info-icon"><img src="'.esc_url(plugin_dir_url( __FILE__ ).'../../assets/admin/dashboard/images/info.svg').'" alt=""></span>';
									echo '<a class="bwd-widgets-demo-icon" target="_blank" href="'.$generalWidget['demo'].'"><img src="'.esc_url(plugin_dir_url( __FILE__ ).'../../assets/admin/dashboard/images/demo.svg').'" alt=""></a>';
									echo '<a class="bwd-widgets-video-icon" target="_blank" href="'.$generalWidget['video'].'"><img src="'.esc_url(plugin_dir_url( __FILE__ ).'../../assets/admin/dashboard/images/video.svg').'" alt=""></a>';
									echo '<a class="bwd-widgets-doc-icon" target="_blank" href="'.$generalWidget['documentation'].'"><img src="'.esc_url(plugin_dir_url( __FILE__ ).'../../assets/admin/dashboard/images/doc.svg').'" alt=""></a>';
								echo '</div>';
							echo '</div>';
							echo '<div class="bwd-widgets-switcher">';
								echo '<label class="bwd-widget-switch">';
            						$inputChecked = get_option($generalWidget['id'], 'off') === 'on' ? 'checked' : '';
									$checkbx = ( !class_exists( 'ProbwdelementorBundle' ) )?'':'checkbox';
									$isPro = $generalWidget['free_pro']==true?'checkbox':$checkbx;
									echo '<input class="bwd-widinput-switch" type="'.$isPro.'" name="'.$generalWidget['id'].'" id="'.$generalWidget['id'].'" '.$inputChecked.'>';
									echo '<span class="bwd-switch-box"></span>';
								echo '</label>';
							echo '</div>';
						echo '</div>';
					echo '</div>';
                endforeach;
            echo '</div>';
        echo '</div>';
			echo '<div class="bwd-widgets-items bwd-sk-wrapper">';
				echo $all_T[1];
				echo '<div class="bwd-widgets-item-container bwd-grid">';
				foreach($cvWidgets as $cvWidget=>$getCV):
					echo '<div class="bwd-sk-cmn bwd-sk-cmn bwd-col-xl-3 col-search">';
						echo '<div class="bwd-widgets-item-wrap">';
                        echo $getCV['new']==true?'<div class="bwd-widget-new-badge">New</div>':'';
                        $freeProText = $getCV['free_pro']==true?esc_html__('Free/Pro','bwd-elementor-addons'):esc_html__('Pro','bwd-elementor-addons');
                        $ifPro = $getCV['free_pro']==true?esc_attr('free-'):'';
							echo '<div class="bwd-widget-'.$ifPro.'pro-badge">'.$freeProText.'</div>';
							echo '<div class="bwd-widgets-title-icon-wrap">';
								echo '<div class="bwd-widgets-title">';
									echo '<h6>'.$getCV['name'].'</h6>';
									echo '<span>Total used - 0</span>';
								echo '</div>';
								echo '<div class="bwd-widgets-info-icons">';
									echo '<span class="bwd-widgets-info-icon"><img src="'.esc_url(plugin_dir_url( __FILE__ ).'../../assets/admin/dashboard/images/info.svg').'" alt=""></span>';
									echo '<a class="bwd-widgets-demo-icon" target="_blank" href="'.$getCV['demo'].'"><img src="'.esc_url(plugin_dir_url( __FILE__ ).'../../assets/admin/dashboard/images/demo.svg').'" alt=""></a>';
									echo '<a class="bwd-widgets-video-icon" target="_blank" href="'.$getCV['video'].'"><img src="'.esc_url(plugin_dir_url( __FILE__ ).'../../assets/admin/dashboard/images/video.svg').'" alt=""></a>';
									echo '<a class="bwd-widgets-doc-icon" target="_blank" href="'.$getCV['documentation'].'"><img src="'.esc_url(plugin_dir_url( __FILE__ ).'../../assets/admin/dashboard/images/doc.svg').'" alt=""></a>';
								echo '</div>';
							echo '</div>';
							echo '<div class="bwd-widgets-switcher">';
								echo '<label class="bwd-widget-switch">';
                                    $inputChecked = get_option($getCV['id'], 'off') === 'on' ? 'checked' : '';
									$checkbx = ( !class_exists( 'ProbwdelementorBundle' ) )?'':'checkbox';
									$isPro = $getCV['free_pro']==true?'checkbox':$checkbx;
									echo '<input class="bwd-widinput-switch" type="'.$isPro.'" name="'.$getCV['id'].'" id="'.$getCV['id'].'" '.$inputChecked.'>';
									echo '<span class="bwd-switch-box"></span>';
								echo '</label>';
							echo '</div>';
						echo '</div>';
					echo '</div>';
				endforeach;
				echo '</div>';
			echo '</div>';
			echo '<div class="bwd-widgets-items bwd-sk-wrapper">';
				echo $all_T[2];
				echo '<div class="bwd-widgets-item-container bwd-grid">';
				$i = 1;
				for ($i; $i <= 13; $i++) :
					echo '<div class="bwd-sk-cmn bwd-sk-cmn bwd-col-xl-3 col-search">';
						echo '<div class="bwd-widgets-item-wrap">';
							echo '<div class="bwd-widget-pro-badge">'.esc_html__('Pro','bwd-elementor-addons').'</div>';
							echo '<div class="bwd-widgets-title-icon-wrap">';
								echo '<div class="bwd-widgets-title">';
									echo '<h6>'.esc_html__('Hero Style '.$i, 'bwd-elementor-addons').'</h6>';
									echo '<span>Total used - 0</span>';
								echo '</div>';
								echo '<div class="bwd-widgets-info-icons">';
									echo '<span class="bwd-widgets-info-icon"><img src="'.esc_url(plugin_dir_url( __FILE__ ).'../../assets/admin/dashboard/images/info.svg').'" alt=""></span>';
									echo '<a class="bwd-widgets-demo-icon" target="_blank" href="https://bestwpdeveloper.com/hero-section/"><img src="'.esc_url(plugin_dir_url( __FILE__ ).'../../assets/admin/dashboard/images/demo.svg').'" alt=""></a>';
									echo '<a class="bwd-widgets-video-icon" target="_blank" href="video-link-'.$i.'"><img src="'.esc_url(plugin_dir_url( __FILE__ ).'../../assets/admin/dashboard/images/video.svg').'" alt=""></a>';
									echo '<a class="bwd-widgets-doc-icon" target="_blank" href="https://bestwpdeveloper.com/documentation"><img src="'.esc_url(plugin_dir_url( __FILE__ ).'../../assets/admin/dashboard/images/doc.svg').'" alt=""></a>';
								echo '</div>';
							echo '</div>';
							echo '<div class="bwd-widgets-switcher">';
								echo '<label class="bwd-widget-switch">';
                                    $inputChecked = get_option('bwdeb-check-hero-widget'.$i, 'off') === 'on' ? 'checked' : '';
									$checkbx = ( !class_exists( 'ProbwdelementorBundle' ) )?'':'checkbox';
									echo '<input class="bwd-widinput-switch" type="'.$checkbx.'" name="bwdeb-check-hero-widget'.$i.'" id="bwdeb-check-hero-widget'.$i.'" '.$inputChecked.'>';
									echo '<span class="bwd-switch-box"></span>';
								echo '</label>';
							echo '</div>';
						echo '</div>';
					echo '</div>';
				endfor;
				echo '</div>';
			echo '</div>';
			echo '<div class="bwd-widgets-items bwd-sk-wrapper">';
				echo $all_T[3];
				echo '<div class="bwd-widgets-item-container bwd-grid">';
				foreach($postWidgets as $postWidget=>$getPost):
					echo '<div class="bwd-sk-cmn bwd-sk-cmn bwd-col-xl-3 col-search">';
						echo '<div class="bwd-widgets-item-wrap">';
                        echo $getPost['new']==true?'<div class="bwd-widget-new-badge">New</div>':'';
                        $freeProText = $getPost['free_pro']==true?esc_html__('Free/Pro','bwd-elementor-addons'):esc_html__('Pro','bwd-elementor-addons');
                        $ifPro = $getPost['free_pro']==true?esc_attr('free-'):'';
							echo '<div class="bwd-widget-'.$ifPro.'pro-badge">'.$freeProText.'</div>';
							echo '<div class="bwd-widgets-title-icon-wrap">';
								echo '<div class="bwd-widgets-title">';
									echo '<h6>'.$getPost['name'].'</h6>';
									echo '<span>Total used - 0</span>';
								echo '</div>';
								echo '<div class="bwd-widgets-info-icons">';
									echo '<span class="bwd-widgets-info-icon"><img src="'.esc_url(plugin_dir_url( __FILE__ ).'../../assets/admin/dashboard/images/info.svg').'" alt=""></span>';
									echo '<a class="bwd-widgets-demo-icon" target="_blank" href="'.$getPost['demo'].'"><img src="'.esc_url(plugin_dir_url( __FILE__ ).'../../assets/admin/dashboard/images/demo.svg').'" alt=""></a>';
									echo '<a class="bwd-widgets-video-icon" target="_blank" href="'.$getPost['video'].'"><img src="'.esc_url(plugin_dir_url( __FILE__ ).'../../assets/admin/dashboard/images/video.svg').'" alt=""></a>';
									echo '<a class="bwd-widgets-doc-icon" target="_blank" href="'.$getPost['documentation'].'"><img src="'.esc_url(plugin_dir_url( __FILE__ ).'../../assets/admin/dashboard/images/doc.svg').'" alt=""></a>';
								echo '</div>';
							echo '</div>';
							echo '<div class="bwd-widgets-switcher">';
								echo '<label class="bwd-widget-switch">';
                                    $inputChecked = get_option($getPost['id'], 'off') === 'on' ? 'checked' : '';
									$checkbx = ( !class_exists( 'ProbwdelementorBundle' ) )?'':'checkbox';
									$isPro = $getPost['free_pro']==true?'checkbox':$checkbx;
									echo '<input class="bwd-widinput-switch" type="'.$isPro.'" name="'.$getPost['id'].'" id="'.$getPost['id'].'" '.$inputChecked.'>';
									echo '<span class="bwd-switch-box"></span>';
								echo '</label>';
							echo '</div>';
						echo '</div>';
					echo '</div>';
				endforeach;
				echo '</div>';
			echo '</div>';
			echo '<div class="bwd-widgets-items bwd-sk-wrapper">';
				echo $all_T[4];
				echo '<div class="bwd-widgets-item-container bwd-grid">';
				foreach($productWidgets as $productWidget=>$getProduct):
					echo '<div class="bwd-sk-cmn bwd-sk-cmn bwd-col-xl-3 col-search">';
						echo '<div class="bwd-widgets-item-wrap">';
                        echo $getProduct['new']==true?'<div class="bwd-widget-new-badge">New</div>':'';
                        $freeProText = $getProduct['free_pro']==true?esc_html__('Free/Pro','bwd-elementor-addons'):esc_html__('Pro','bwd-elementor-addons');
                        $ifPro = $getProduct['free_pro']==true?esc_attr('free-'):'';
							echo '<div class="bwd-widget-'.$ifPro.'pro-badge">'.$freeProText.'</div>';
							echo '<div class="bwd-widgets-title-icon-wrap">';
								echo '<div class="bwd-widgets-title">';
									echo '<h6>'.$getProduct['name'].'</h6>';
									echo '<span>Total used - 0</span>';
								echo '</div>';
								echo '<div class="bwd-widgets-info-icons">';
									echo '<span class="bwd-widgets-info-icon"><img src="'.esc_url(plugin_dir_url( __FILE__ ).'../../assets/admin/dashboard/images/info.svg').'" alt=""></span>';
									echo '<a class="bwd-widgets-demo-icon" target="_blank" href="'.$getProduct['demo'].'"><img src="'.esc_url(plugin_dir_url( __FILE__ ).'../../assets/admin/dashboard/images/demo.svg').'" alt=""></a>';
									echo '<a class="bwd-widgets-video-icon" target="_blank" href="'.$getProduct['video'].'"><img src="'.esc_url(plugin_dir_url( __FILE__ ).'../../assets/admin/dashboard/images/video.svg').'" alt=""></a>';
									echo '<a class="bwd-widgets-doc-icon" target="_blank" href="'.$getProduct['documentation'].'"><img src="'.esc_url(plugin_dir_url( __FILE__ ).'../../assets/admin/dashboard/images/doc.svg').'" alt=""></a>';
								echo '</div>';
							echo '</div>';
							echo '<div class="bwd-widgets-switcher">';
								echo '<label class="bwd-widget-switch">';
                                    $inputChecked = get_option($getProduct['id'], 'off') === 'on' ? 'checked' : '';
									$checkbx = ( !class_exists( 'ProbwdelementorBundle' ) )?'':'checkbox';
									$isPro = $getProduct['free_pro']==true?'checkbox':$checkbx;
									echo '<input class="bwd-widinput-switch" type="'.$isPro.'" name="'.$getProduct['id'].'" id="'.$getProduct['id'].'" '.$inputChecked.'>';
									echo '<span class="bwd-switch-box"></span>';
								echo '</label>';
							echo '</div>';
						echo '</div>';
					echo '</div>';
				endforeach;
				echo '</div>';
			echo '</div>';
		echo '</div>';
	echo '</div>';
