<?php
if ( ! defined( 'ABSPATH' ) ) exit;
/**
 * 
 * @this is dashboard file. Here have the dashboard design
 * 
 */
	// Added  the all filed here
	add_settings_field(
		'bwdeb-plugin-meet-the-team',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-testimonials',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-creative-button',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-accordion',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-masking-effect',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-service-showcase',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-promo-box',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-service-flip-box',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-flip-box-carousel',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-step-flip-box',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-team-flip-box',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-map-masking',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-creative-list',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-dual-heading',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-back-to-top',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-call-to-action',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-icon-box',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-dual-button',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-honeycombs',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);

	// Next from Dual Button
	add_settings_field(
		'bwdeb-plugin-awesome-step',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-counter',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-image-hover-effect',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-countdown',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-animated-heading',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-filterable-gallery',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-pricing-table',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-social-icon',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-creative-tab',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-author-bio',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-animated-link',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-business-hours',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-image-shape',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-fancy-heading',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-progress-bar',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-image-accordion',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-image-compare',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-timeline',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-blockquote',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-video-popup',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-image-stack-group',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-masking-video',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-image-swap',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-profile-card',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-photo-stack',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-image-scroll',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-ihover',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-webinar-info',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-circle-info',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-coupon-code',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-unique-headers',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-click-to-contact',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-popup',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-data-table',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-advanced-slider',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-slide-anything',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-contact-form-7-styler',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-image-hotspot',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-logo-carousel',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-logo-grid',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-logo-filter',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-team-carousel',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-unfold',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-code-highlighter',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-lottie-animation',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-breadcrumb',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-brand-logo-showcase',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-info-download-button',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-effective-pre-loader',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-bar-chart',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-social-share',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-background-switcher',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-lord-icon',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-cart-flipper',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-ajax-data-table',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-con-swi-pls',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-img-rev-widg',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-img-unfold-kit',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-modern-feature-list',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-offcanvasmagic',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-privacy-content-locker',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-viewpdf',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-progress-master-kit',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-restaurant-price-menu',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-sales-promotion-offer',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-profile-showcas',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-product-features-w',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-tooltip-mastery',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-employee-profile-identity',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-horizontal-timeline-slider',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-threesixty-rotation-view',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-widget-template',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-pssx',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-blmx1',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-blmx2',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-blmx3',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-svpx',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-txsx',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-vsix',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);

	add_settings_field(
		'bwdeb-plugin-cv-builder',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-cv-about',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-cv-contact',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-cv-education',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-cv-experience',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-cv-footer',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-cv-header',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-cv-hobby',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-cv-language',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-cv-reference',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-cv-skill',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-check-hero-widget1',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-check-hero-widget2',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-check-hero-widget3',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-check-hero-widget4',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-check-hero-widget5',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-check-hero-widget6',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-check-hero-widget7',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-check-hero-widget8',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-check-hero-widget9',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-check-hero-widget10',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-check-hero-widget11',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-check-hero-widget12',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-check-hero-widget13',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-post-grid',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-post-list',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-post-tiles',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-post-accordion',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-post-timeline',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-masonary-blog-post',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-post-image-accordion',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-single-post-slider',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-news-ticker',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-creative-post-carousel',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-post-prestige-portfolio',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-apostst',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);

	add_settings_field(
		'bwdeb-plugin-product-grid',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-product-list',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-product-tiles',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-product-carousel',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-product-category-grid',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-product-category-tiles',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-product-accordion',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-product-image-accordion',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-product-list-carousel',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-product-timeline',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-content-switcher',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-related-product',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-product-category-carousel',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-featured-product',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-product-compare',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-woo-cat-gallery',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-woop-multi-action',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-plugin-woop-wish-cont',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-woop-vendors',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-twpx',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-extn-tooltip',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-extn-link',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-extn-protctn',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-csstrnsm',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-flanime',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-duplicate',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-3d-text',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-notation',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-confetti-effects',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-cursor-effects',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-reveal-effects',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-tile-scroll',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-section-sticky',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-scroll-box',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-background-particles',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-xd-copy',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-custom-jscss',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-section-parallax',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-gra-anim-bg',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-backdrop-filter',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-line-grid',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-cursor-img-parallax',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
	add_settings_field(
		'bwdeb-live-copy',
		'',
		'bwdeb_plugin_function_for_datas_callback',
		'bwdeb-plugin-main-menu',
		'bwdeb-plugin-switch-section'
	);
  
  // Registered the add switch control here
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-meet-the-team' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-testimonials' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-creative-button' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-accordion' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-masking-effect' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-service-showcase' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-promo-box' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-service-flip-box' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-flip-box-carousel' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-step-flip-box' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-team-flip-box' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-map-masking' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-creative-list' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-dual-heading' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-back-to-top' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-call-to-action' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-icon-box' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-dual-button' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-honeycombs' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-awesome-step' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-counter' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-image-hover-effect' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-countdown' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-animated-heading' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-filterable-gallery' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-pricing-table' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-social-icon' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-creative-tab' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-author-bio' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-animated-link' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-business-hours' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-image-shape' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-fancy-heading' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-progress-bar' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-image-accordion' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-image-compare' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-timeline' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-blockquote' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-video-popup' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-image-stack-group' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-masking-video' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-image-swap' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-profile-card' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-photo-stack' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-image-scroll' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-ihover' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-webinar-info' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-circle-info' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-coupon-code' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-unique-headers' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-click-to-contact' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-popup' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-data-table' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-advanced-slider' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-slide-anything' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-contact-form-7-styler' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-image-hotspot' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-logo-carousel' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-logo-grid' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-logo-filter' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-team-carousel' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-unfold' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-code-highlighter' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-lottie-animation' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-breadcrumb' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-brand-logo-showcase' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-info-download-button' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-effective-pre-loader' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-bar-chart' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-social-share' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-background-switcher' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-lord-icon' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-cart-flipper' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-ajax-data-table' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-con-swi-pls' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-img-rev-widg' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-img-unfold-kit' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-modern-feature-list' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-offcanvasmagic' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-privacy-content-locker' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-viewpdf' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-progress-master-kit' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-restaurant-price-menu' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-sales-promotion-offer' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-profile-showcas' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-product-features-w' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-tooltip-mastery' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-employee-profile-identity' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-horizontal-timeline-slider' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-threesixty-rotation-view' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-widget-template' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-pssx' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-blmx1' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-blmx2' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-blmx3' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-svpx' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-txsx' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-vsix' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-cv-builder' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-cv-about' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-cv-contact' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-cv-education' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-cv-experience' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-cv-footer' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-cv-header' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-cv-hobby' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-cv-language' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-cv-reference' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-cv-skill' 
	);
	register_setting(
		'bwdeb-plugin-settings',
		'bwdeb-check-hero-widget1'
	);
	register_setting(
		'bwdeb-plugin-settings',
		'bwdeb-check-hero-widget2'
	);
	register_setting(
		'bwdeb-plugin-settings',
		'bwdeb-check-hero-widget3'
	);
	register_setting(
		'bwdeb-plugin-settings',
		'bwdeb-check-hero-widget4'
	);
	register_setting(
		'bwdeb-plugin-settings',
		'bwdeb-check-hero-widget5'
	);
	register_setting(
		'bwdeb-plugin-settings',
		'bwdeb-check-hero-widget6'
	);
	register_setting(
		'bwdeb-plugin-settings',
		'bwdeb-check-hero-widget7'
	);
	register_setting(
		'bwdeb-plugin-settings',
		'bwdeb-check-hero-widget8'
	);
	register_setting(
		'bwdeb-plugin-settings',
		'bwdeb-check-hero-widget9'
	);
	register_setting(
		'bwdeb-plugin-settings',
		'bwdeb-check-hero-widget10'
	);
	register_setting(
		'bwdeb-plugin-settings',
		'bwdeb-check-hero-widget11'
	);
	register_setting(
		'bwdeb-plugin-settings',
		'bwdeb-check-hero-widget12'
	);
	register_setting(
		'bwdeb-plugin-settings',
		'bwdeb-check-hero-widget13'
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-post-grid' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-post-list' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-post-tiles' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-post-accordion' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-post-timeline' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-masonary-blog-post' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-post-image-accordion' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-single-post-slider' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-news-ticker' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-creative-post-carousel' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-post-prestige-portfolio' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-apostst' 
	);

	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-product-grid' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-product-list' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-product-tiles' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-product-carousel' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-product-category-grid' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-product-category-tiles' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-product-accordion' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-product-image-accordion' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-product-list-carousel' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-product-timeline' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-content-switcher' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-related-product' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-product-category-carousel' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-featured-product' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-product-compare' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-woo-cat-gallery' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-woop-multi-action' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-plugin-woop-wish-cont' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-woop-vendors' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-twpx' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-extn-tooltip' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-extn-link' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-extn-protctn' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-csstrnsm' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-flanime' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-duplicate' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-3d-text' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-notation' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-confetti-effects' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-cursor-effects' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-reveal-effects' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-tile-scroll' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-section-sticky' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-scroll-box' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-background-particles' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-xd-copy' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-custom-jscss' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-section-parallax' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-gra-anim-bg' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-backdrop-filter' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-line-grid' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-cursor-img-parallax' 
	);
	register_setting( 
		'bwdeb-plugin-settings', 
		'bwdeb-live-copy' 
	);